language: java

jdk:
  - openjdk14

sudo: false

notifications:
  email:
    recipients:
      - rail.shamsemukhametov@mail.ru
    on_success: never # default: change
    on_failure: always # default: always

